---
abstract: 'Readonly at BEGIN time'
author:
  - "Curtis \"Ovid\" Poe <ovid@cpan.org>"
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3601'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Readonly-BeginLift
provides:
  Readonly::BeginLift:
    file: lib/Readonly/BeginLift.pm
    version: 0.03
requires:
  Devel::BeginLift: 0.001002
  Readonly: 1.03
  parent: 0.221
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
